language: php

php:
  - 8.2
  - 8.3
  - 8.4

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls
  - composer install --prefer-source

script:
  - composer check-style
  - composer tests-ci

after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true

sudo: false

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
